<?php
declare(strict_types=1);

include __DIR__ . '/../vendor/autoload.php';

use Ctw\Http\HttpStatus;

$reflectionClass = new ReflectionClass(HttpStatus::class);

foreach (array_keys($reflectionClass->getConstants()) as $const) {
    echo sprintf('HttpStatus::%s', $const);
    echo PHP_EOL;
}

// HttpStatus::FILENAME
// HttpStatus::STATUS_CONTINUE
// HttpStatus::STATUS_SWITCHING_PROTOCOLS
// HttpStatus::STATUS_PROCESSING
// HttpStatus::STATUS_EARLY_HINTS
// HttpStatus::STATUS_OK
// HttpStatus::STATUS_CREATED
// HttpStatus::STATUS_ACCEPTED
// HttpStatus::STATUS_NON_AUTHORITATIVE_INFORMATION
// HttpStatus::STATUS_NO_CONTENT
// HttpStatus::STATUS_RESET_CONTENT
// HttpStatus::STATUS_PARTIAL_CONTENT
// HttpStatus::STATUS_MULTI_STATUS
// HttpStatus::STATUS_ALREADY_REPORTED
// HttpStatus::STATUS_IM_USED
// HttpStatus::STATUS_MULTIPLE_CHOICES
// HttpStatus::STATUS_MOVED_PERMANENTLY
// HttpStatus::STATUS_FOUND
// HttpStatus::STATUS_SEE_OTHER
// HttpStatus::STATUS_NOT_MODIFIED
// HttpStatus::STATUS_USE_PROXY
// HttpStatus::STATUS_RESERVED
// HttpStatus::STATUS_TEMPORARY_REDIRECT
// HttpStatus::STATUS_PERMANENT_REDIRECT
// HttpStatus::STATUS_BAD_REQUEST
// HttpStatus::STATUS_UNAUTHORIZED
// HttpStatus::STATUS_PAYMENT_REQUIRED
// HttpStatus::STATUS_FORBIDDEN
// HttpStatus::STATUS_NOT_FOUND
// HttpStatus::STATUS_METHOD_NOT_ALLOWED
// HttpStatus::STATUS_NOT_ACCEPTABLE
// HttpStatus::STATUS_PROXY_AUTHENTICATION_REQUIRED
// HttpStatus::STATUS_REQUEST_TIMEOUT
// HttpStatus::STATUS_CONFLICT
// HttpStatus::STATUS_GONE
// HttpStatus::STATUS_LENGTH_REQUIRED
// HttpStatus::STATUS_PRECONDITION_FAILED
// HttpStatus::STATUS_PAYLOAD_TOO_LARGE
// HttpStatus::STATUS_URI_TOO_LONG
// HttpStatus::STATUS_UNSUPPORTED_MEDIA_TYPE
// HttpStatus::STATUS_RANGE_NOT_SATISFIABLE
// HttpStatus::STATUS_EXPECTATION_FAILED
// HttpStatus::STATUS_IM_A_TEAPOT
// HttpStatus::STATUS_MISDIRECTED_REQUEST
// HttpStatus::STATUS_UNPROCESSABLE_ENTITY
// HttpStatus::STATUS_LOCKED
// HttpStatus::STATUS_FAILED_DEPENDENCY
// HttpStatus::STATUS_TOO_EARLY
// HttpStatus::STATUS_UPGRADE_REQUIRED
// HttpStatus::STATUS_PRECONDITION_REQUIRED
// HttpStatus::STATUS_TOO_MANY_REQUESTS
// HttpStatus::STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE
// HttpStatus::STATUS_UNAVAILABLE_FOR_LEGAL_REASONS
// HttpStatus::STATUS_INTERNAL_SERVER_ERROR
// HttpStatus::STATUS_NOT_IMPLEMENTED
// HttpStatus::STATUS_BAD_GATEWAY
// HttpStatus::STATUS_SERVICE_UNAVAILABLE
// HttpStatus::STATUS_GATEWAY_TIMEOUT
// HttpStatus::STATUS_VERSION_NOT_SUPPORTED
// HttpStatus::STATUS_VARIANT_ALSO_NEGOTIATES
// HttpStatus::STATUS_INSUFFICIENT_STORAGE
// HttpStatus::STATUS_LOOP_DETECTED
// HttpStatus::STATUS_NOT_EXTENDED
// HttpStatus::STATUS_NETWORK_AUTHENTICATION_REQUIRED
